docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - 'Theory and Usage': usage.md
    - 'Refining ACLs': refining.md
    - 'Advanced Usage': advanced.md
site_name: laminas-permissions-acl
site_description: Laminas\Permissions.acl
repo_url: 'https://github.com/laminas/laminas-permissions-acl'
